f=open('app/booking/complete/page.tsx','r',encoding='utf-8') 
content=f.read() 
f.close() 
content=content.replace("booking.payment_method === 'bank_transfer'","(booking.payment_method as string) === 'bank_transfer'") 
content=content.replace("booking.payment_method === 'bank'","(booking.payment_method as string) === 'bank'") 
f=open('app/booking/complete/page.tsx','w',encoding='utf-8') 
f.write(content) 
f.close() 
print('done') 
